#!/usr/bin/env sh

# Github Pages user account.
USER=swatson555

# Get target repository.
if [[ ! -e $USER.github.io/ ]] ; then
    git clone https://github.com/$USER/$USER.github.io.git
fi

# Sync repository with the build.
rsync --checksum -a _site/. $USER.github.io/

# Display status of target repository.
pushd $USER.github.io/
git status
popd
